### ISSUE TITLE
 Collection  is missing pid for item 0.

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#72]
**Describe the bug**
When trying to use wax:pagemaster on a collection, it fails with a MissingPid error

**Screenshots**
```$ bundle exec rake wax:pagemaster creators --trace
** Invoke wax:pagemaster (first_time)
** Execute wax:pagemaster
rake aborted!
WaxTasks::Error::MissingPid: Collection  is missing pid for item 0.
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/utils.rb:23:in `block in assert_pids'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/utils.rb:23:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/utils.rb:23:in `each_with_index'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/utils.rb:23:in `assert_pids'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/collection.rb:57:in `ingest_file'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/pagemaster_collection.rb:18:in `initialize'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:61:in `new'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:61:in `block in pagemaster'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:60:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:60:in `pagemaster'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/tasks/pagemaster.rake:9:in `block (2 levels) in <top (required)>'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
D:/ruby/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
D:/ruby/bin/rake:22:in `load'
D:/ruby/bin/rake:22:in `<main>'
Tasks: TOP => wax:pagemaster
```

**Additional context**
Here's my collection definition : 

```
collections/fr/creators:
    output: true
    source: creators.json
    id_key: tagname
    layout: tag_fr
```

Here's the JSON data file used for this :
[creators.json.txt](https://github.com/mnyrop/wax_tasks/files/2360297/creators.json.txt)

**Comment by AxelTerizaki** [comment]
Forgot to mention this collection works fine with the pagemaster gem alone :)

**Comment by AxelTerizaki** [comment]
Okay, I've just found the "Read More" link and saw each element must have a pid column...

Couldn't it behave just like the pagemaster gem you made where you can specify an index to use to name files ? This is also better for search engines to have pages named after something instead of unique IDs.

This part of our dataset can't use UUIDs or even numerical IDs. Items are identified by their name (which is supposed to be unique).

**Comment by mnyrop** [comment]
You could create a slugified version of the name for each item as its `pid`, either with open refine or a rake task? Wax tasks is tied to a set `pid` field because wax_tasks is much more complicated. It needs to enforce image filenames and more from a given persistent ID, whereas pagemaster (the gem) is not part of a suite of modules and thus can be more flexible. 

Happy to give tips on generating `pid`s, but I'm closing this issue because the `pid` enforcement definitely won't be changing for this gem.

**Comment by AxelTerizaki** [comment]
The problem with this is that for some collections I don't have any PID to use, and don't plan to use one at all. My data comes from a SQLite database so I can't easily slugify it either from inside the database engine.

I'll probably have to go through loops and loops to get some kind of "pid" wax_tasks can use. Might as well wait for you to implement https://github.com/mnyrop/pagemaster/issues/13 in this case.
