### ISSUE TITLE
wax:lunr fails if one field is empty

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#73]
**Describe the bug**
When using wax:lunr, it complains about not being able to load a particular file from the collection. The file does exist, but one of the fields referenced in the fields: option is empty

**To Reproduce**
1. Try to generate pages with wax:pagemaster with the data provided. 5918 files should be generated
2. Try to run wax:lunr

**Expected behavior**
Shouldn't abort

**Screenshots**
```
$ bundle exec rake wax:pagemaster fr/karas
5918 pages were generated to fr/karas directory.

$ bundle exec rake wax:lunr --trace
** Invoke wax:lunr (first_time)
** Execute wax:lunr
rake aborted!
WaxTasks::Error::LunrPageLoad: Cannot load page fr/karas/050472ab-93d3-41be-a8a7-985c37c6d43a.md
undefined method `normalize' for nil:NilClass
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:36:in `rescue in block in ingest_pages'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:33:in `block in ingest_pages'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:32:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:32:in `ingest_pages'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:19:in `initialize'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `new'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `block in lunr'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `map!'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `lunr'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/tasks/lunr.rake:7:in `block (2 levels) in <top (required)>'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
D:/ruby/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
D:/ruby/bin/rake:22:in `load'
D:/ruby/bin/rake:22:in `<main>'

Caused by:
NoMethodError: undefined method `normalize' for nil:NilClass
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:55:in `block in load_page'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:55:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:55:in `load_page'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:34:in `block in ingest_pages'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:32:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:32:in `ingest_pages'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/lunr_collection.rb:19:in `initialize'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `new'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `block in lunr'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `map!'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/wax_tasks/task_runner.rb:73:in `lunr'
D:/ruby/lib/ruby/gems/2.4.0/gems/wax_tasks-0.3.0/lib/tasks/lunr.rake:7:in `block (2 levels) in <top (required)>'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
D:/ruby/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
D:/ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
D:/ruby/bin/rake:22:in `load'
D:/ruby/bin/rake:22:in `<main>'
Tasks: TOP => wax:lunr

```

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Ruby 2.4.1p111

**Additional context**

Here's the data file : 

[karas.json.txt](https://github.com/mnyrop/wax_tasks/files/2375220/karas.json.txt)

Here's part of my config file : 

```
collections:
  fr/karas:
    output: true
    source: karas.json
    layout: kara_fr
    lunr_index:
      content: false
      fields: [ title, serie, type, creator, author, singer, songwriter, tags ]
```

Some of the data has no "serie", which is okay for this particular item. Maybe testing if the field is empty before trying to index it would fix such errors?

Thanks in advance :)

**Comment by mnyrop** [comment]
Try replacing `gem 'wax_tasks'` in your `Gemfile` with 
```
gem 'wax_tasks', :git => 'https://github.com/mnyrop/wax_tasks.git', :branch => 'beta'
```
And rerun `wax:lunr`.

Also, can you link to a public repo? It might help me understand all of your issues

**Comment by AxelTerizaki** [comment]
I'll try that out tomorrow. You can check the repo using wax_tasks here : 

https://lab.shelter.moe/karaokemugen/sites/mugen-site/tree/wax_task

**Comment by AxelTerizaki** [comment]
Got this on install : ```
Using wax_tasks 0.3.1 (was 0.3.0) from https://github.com/mnyrop/wax_tasks.git (at beta@2bd086f)
```

Tried to re-run wax:lunr : 

```$ bundle exec rake wax:lunr
rake aborted!
WaxTasks::Error::LunrPageLoad: Cannot load page fr/karas/050472ab-93d3-41be-a8a7-985c37c6d43a.md
undefined method `lunr_normalize' for nil:NilClass


Caused by:
NoMethodError: undefined method `lunr_normalize' for nil:NilClass

Tasks: TOP => wax:lunr
```

Still getting the same error.

The .md file contains : 

```
---
pid: 050472ab-93d3-41be-a8a7-985c37c6d43a
kid: 050472ab-93d3-41be-a8a7-985c37c6d43a
title: Ura-omote Lovers
duration: 187
audiogain: -11.32
year: '2009'
subfile: JAP - Miku Hatsune - MV - Ura-omote Lovers.ass
karafile: JAP - Miku Hatsune - MV - Ura-omote Lovers.kara
mediasize: 11761833
mediafile: JAP - Miku Hatsune - MV - Ura-omote Lovers.mp4
dateadded: 1522968686
datemodif: 1533471991
order: ''
serie:
NORM_serie:
singer: Miku Hatsune
type: TYPE_MV
creator: NO_TAG
lang: jpn
author: Bakaclub
tags: TAG_VOCALOID
songwriter: wowaka
permalink: "/fr/karas/050472ab-93d3-41be-a8a7-985c37c6d43a.html"
layout: kara_fr
---
```

I think it dstill doesn't like that `serie:` is empty.

**Comment by mnyrop** [comment]
Should work as of commit #6a5a45a on beta. I tried on your data, so I think this time it will be good if you use 

```
gem 'wax_tasks', :git => 'https://github.com/mnyrop/wax_tasks.git', :branch => 'beta'
```

If so, I'll release it as a patch for 0.3.1.

<img src='http://oi64.tinypic.com/34g8009.jpg'/>
